stages:
  - build
  - deploy

pages:
  tags:
    - windows
  stage: build
  script:
  - npm install hexo-cli -g --registry=https://registry.npmmirror.com --disturl=https://npmmirror.com/mirrors/node --no-progress
  - npm install --registry=https://registry.npmmirror.com --disturl=https://npmmirror.com/mirrors/node --no-progress --frozen-lockfile
  - hexo clean
  - hexo generate
  artifacts:
    paths:
    - public
  only:
  - master

deploy-upyun:
  tags:
    - ftp
  stage: deploy
  script:
    - lftp -c "set sftp:connect-program 'ssh -oStrictHostKeyChecking=no';set sftp:auto-confirm yes;open -u $FTP_USERNAME,$FTP_PASSWORD -p $FTP_PORT $FTP_HOST;mirror -Rv public / --ignore-time --transfer-all --parallel=50 --exclude-glob .git* --exclude .git/" || true
  only:
    - master
  cache: {}
