stages:
  - build
  - deploy

pages:
  image: node:8.11.2
  cache:
    paths:
    - node_modules/
  stage: build
  script:
  - npm install hexo-cli -g --registry=http://nexus3.nexus3:8081/repository/npm/
  - npm install --registry=http://nexus3.nexus3:8081/repository/npm/
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master

deploy-upyun:
  image: mwienk/docker-lftp:latest
  stage: deploy
  script:
    - lftp -c "set ftp:ssl-allow no;open -u $FTP_USERNAME,$FTP_PASSWORD -p $FTP_PORT $FTP_HOST;mirror -Rv public / --ignore-time --transfer-all --parallel=50 --exclude-glob .git* --exclude .git/" || true
  only:
    - master
  cache: {}
